paths:
# Movies
  movies.genres:
    verb: get
    path: movies/genres
    description: Get genres
  movies.single:
    verb: get
    path: movies/:id
    description: Get full details of film

# Users
  users.single:
    verb: get
    path: users/:id
    description: Get user if me get full details

# Comments
  comments.gets:
    verb: get
    path: comments/:imdbId
    description: Get comments by movie
  comments.add:
    verb: post
    path: comments/:imdbId
    description: Get comments by movie


# Auth CB
  auth.local:
    verb: post
    path: auth/login
    description: Omiauth login
  auth.facebook:
    verb: get
    path: auth/facebook
    description: Omiauth facebook
  auth.fortyTwo:
    verb: get
    path: auth/42
    description: Omiauth 42
  auth.twitter:
    verb: get
    path: auth/twitter
    description: Omiauth Twitter
  auth.github:
    verb: get
    path: auth/github
    description: Omiauth Github
  auth.google:
    verb: get
    path: auth/google
    description: Omiauth Google
  # auth.spotify:
  #   verb: get
  #   path: auth/spotify
  #   description: Omiauth Spotify
# Auth CB
  auth.localCB:
    verb: get
    path: auth/local/cb
    description: Omiauth login
  auth.facebookCB:
    verb: get
    path: auth/facebook/cb
  auth.twitterCB:
    verb: get
    path: auth/twitter/cb
  auth.fortyTwoCB:
    verb: get
    path: auth/42/cb
  auth.githubCB:
    verb: get
    path: auth/github/cb
  auth.googleCB:
    verb: get
    path: auth/google/cb
  # auth.spotifyCB:
  #   verb: get
  #   path: auth/spotify/cb
