paths:
  movies.genres:
    verb: get
    path: movies/genres
    description: Get genres
    parameters: no
  movies.single:
    verb: get
    path: movies/:id
    description: Get full details of film
    parameters: no
  users.login:
    verb: post
    path: users/login
    description: Get full details of film
    parameters: no
  users.single:
    verb: get
    path: users/:id
    description: Get user if me get full details
    parameters: no
  auth.fortyTwo:
    verb: get
    path: auth/42
    description: Omiauth 42
